import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import { GlobalChat } from "@/components/GlobalChat";
import { AuthProvider } from '@/lib/auth-context';
import { ToastContainer } from "react-toastify";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
     
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          
          <Navbar />
          {children}
          <GlobalChat />
        </body>
      
    </AuthProvider>
    </html>
  );
}
